macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  skip: "changesIncludeOnly('logo/*', '**.md')"
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.3.0/Contents/Home
    APP_PLATFORM: macos # used in release script
    APP_ARCH: aarch64
    APP_TEST_ENV: native
    GITHUB_TOKEN: ENCRYPTED[2dfdcafc7d54acf9defc1b020a2d99bc5ac4bef2a50ec5e44f22cece9abb159b4df4a5f26abee3bb5e3efe52c544a561]
  script: |
    sudo script/install-clojure
    sudo script/install-leiningen
    script/install-graalvm
    export PATH=$GRAALVM_HOME/bin:$PATH
    export JAVA_HOME=$GRAALVM_HOME
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version

    script/compile

    # script/test
    # script/run_lib_tests

    VERSION=$(cat resources/POD_BABASHKA_BUDDY_VERSION)
    arch=${BABASHKA_ARCH:-amd64}
    archive="pod-babashka-buddy-$VERSION-$APP_PLATFORM-$arch.zip"
    zip "$archive" pod-babashka-buddy
    bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dir .
    ./bb release-artifact --file "$archive" || true
  binaries_artifacts:
    path: "pod-babashka-buddy*.zip"
