#!/usr/bin/env bash

set -eo pipefail

rm -rf /tmp/release
mkdir -p /tmp/release
cp pod-babashka-buddy /tmp/release
VERSION=$(cat resources/POD_BABASHKA_BUDDY_VERSION)

pushd /tmp/release

## release binary as zip archive

APP_ARCH=${APP_ARCH:-amd64}

zip "pod-babashka-buddy-$VERSION-$APP_PLATFORM-$APP_ARCH.zip" pod-babashka-buddy

## cleanup

rm pod-babashka-buddy

popd

bb release-artifact --file "/tmp/release/pod-babashka-buddy-$VERSION-$APP_PLATFORM-$APP_ARCH.zip"
