#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

clojure -X:native:uberjar

"$GRAALVM_HOME/bin/gu" install native-image

"$GRAALVM_HOME/bin/native-image" \
    -cp "pod-babashka-buddy.jar" \
    -H:Name=pod-babashka-buddy \
    -H:+ReportExceptionStackTraces \
    --initialize-at-build-time  \
    -H:EnableURLProtocols=jar \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g" \
    pod.babashka.buddy
