#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

clojure -T:build uber

"$GRAALVM_HOME/bin/gu" install native-image

args=(-jar "pod-babashka-buddy.jar"
      -H:Name=pod-babashka-buddy
      -H:+ReportExceptionStackTraces
      --initialize-at-build-time
      --features=graalvm.feature.BouncyCastleFeature
      -H:EnableURLProtocols=jar
      --report-unsupported-elements-at-runtime
      -H:ReflectionConfigurationFiles=reflection-config.json
      --verbose
      --no-fallback
      --no-server
      "-J-Xmx3g"
     )

if [ "$BABASHKA_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$BABASHKA_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+StaticExecutableWithDynamicLibC")
    fi
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"
